Array implementation
SarkisKhachatryan/cpp_implementation pull request #1
Opened 2021-04-27 16:59 UTC by SarkisKhachatryan

2021-04-29 05:57 UTC, lusineghazarosyan requested changes

2021-04-29 05:57 UTC, lusineghazarosyan commented on container/array.hpp
> +    std::size_t _size;
I guess there is no need to keep size as a member, because N already represents size

2021-04-29 05:57 UTC, lusineghazarosyan commented on container/array.hpp
> +        for (size_t i = 0; i < _size - 1; ++i) {
_size -1 ???  maybe _size?? In this case you will not initialize _data[_size-1]

2021-04-29 05:57 UTC, lusineghazarosyan commented on container/array.hpp
> +    array(std::initializer_list<T> list) : _size(N) {
Have you tested this function ? It won't work right

2021-04-29 05:57 UTC, lusineghazarosyan commented on container/array.hpp
> +            auto it = list.begin();
Have a closer look here . You are initializing your array's all elements with list's first one .

2021-04-29 05:57 UTC, lusineghazarosyan commented on container/array.hpp
> +            _data[i] = rhs_data[i];
This won't work as you intent!!! Have a closer look to your loop . You are incrementing both your rhs_data and it's index

2021-04-29 05:57 UTC, lusineghazarosyan commented on container/array.hpp
> +            _data[i] = std::move(rhs_data[i]);
The same here

2021-04-29 05:57 UTC, lusineghazarosyan commented on container/array.hpp
> +    const T* data() const {
I think having non-const overload of data() is a good Idea. For example you want to  read from an istream to your container.

2021-04-29 05:57 UTC, lusineghazarosyan commented on container/array.hpp
> +    T _data[N];
Here is assumed that T is default constructable . Let's change this ))) (I also did this and know I see that this is not generic)))

2021-05-02 10:16 UTC, SarkisKhachatryan commented on container/array.hpp
> +    std::size_t _size;
agree. ty

2021-05-02 10:17 UTC, SarkisKhachatryan commented on container/array.hpp
> +        for (size_t i = 0; i < _size - 1; ++i) {
yup

2021-05-02 10:17 UTC, SarkisKhachatryan commented on container/array.hpp
> +    array(std::initializer_list<T> list) : _size(N) {
right

2021-05-02 10:28 UTC, SarkisKhachatryan commented on container/array.hpp
> +            auto it = list.begin();
yup )

2021-05-02 13:37 UTC, SarkisKhachatryan commented on container/array.hpp
> +            _data[i] = rhs_data[i];
yup

2021-05-02 13:37 UTC, SarkisKhachatryan commented on container/array.hpp
> +            _data[i] = std::move(rhs_data[i]);
done

2021-05-02 13:38 UTC, SarkisKhachatryan commented on container/array.hpp
> +    const T* data() const {
only non-const is enough?

2021-05-02 13:40 UTC, SarkisKhachatryan commented on container/array.hpp
> +    T _data[N];
what should we do? use `std::is_default_constructible`?

2021-05-05 05:53 UTC, lusineghazarosyan commented on container/array.hpp
> +    constexpr array& operator=(array& rhs);
what is the use of this  ????

2021-05-05 05:53 UTC, lusineghazarosyan commented on container/array.hpp
> +    [[nondiscard]] constexpr bool empty() const noexcept;
[[nodiscard]] )) A typo here .

2021-05-05 05:53 UTC, lusineghazarosyan commented on container/array.hpp
> +     * default constructor, all elements are zero initialized
zero initialized??? Maybe default ???

2021-05-05 05:53 UTC, lusineghazarosyan commented on container/array.hpp
> +        _data[i] = *it;
There is a beautiful way to combine this 2. Just write `_data[i] = *it++`

2021-05-05 05:53 UTC, lusineghazarosyan commented on container/array.hpp
> +    constexpr array& operator=(array&& rhs) noexcept;
You can't say this is noexcept , until the move = of value_type is noexcept !)))

2021-05-05 05:53 UTC, lusineghazarosyan commented on container/array.hpp
> +    constexpr reference operator[](size_type pos);
As I see you are marking noexcept , this is noexcept

2021-05-05 05:53 UTC, lusineghazarosyan commented on container/array.hpp
> +    constexpr const_reference operator[](size_type pos) const;
As I see you are marking noexcept , this is noexcept

2021-05-05 05:53 UTC, lusineghazarosyan commented on container/array.hpp
> +    constexpr reference front();
Noexcept ass well

2021-05-05 05:53 UTC, lusineghazarosyan commented on container/array.hpp
> +    constexpr const_reference front() const;
Noexcept

2021-05-05 05:53 UTC, lusineghazarosyan commented on container/array.hpp
> +    constexpr reference back();
noexcept

2021-05-05 05:53 UTC, lusineghazarosyan commented on container/array.hpp
> +    constexpr const_reference back() const;
noexcept

2021-05-05 05:53 UTC, lusineghazarosyan commented on container/array.hpp
> +    constexpr pointer data();
noexcept

2021-05-05 05:53 UTC, lusineghazarosyan commented on container/array.hpp
> +    constexpr const_pointer data() const;
noexcept

2021-05-05 05:53 UTC, lusineghazarosyan commented on container/array.hpp
> +        std::swap(_data[i], rhs[i]);
There is a great thing to do in this kind of situations 
`using std::swap;
swap(_data[i],rhs[i]);`
This will enable argument dependent lookup ))

2021-05-05 05:55 UTC, lusineghazarosyan commented
Actually great work !!!! )))) Well done )

2021-06-03 21:11 UTC, merged